server:
  port: 50309

spring:
  application:
    name: oAuth

  data:
    mongodb:
#      authentication-database:
#      username:
#      password:
      database: local
      port: 27017
      host: localhost


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
